# Generated by Django 5.2.4 on 2025-07-07 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(auto_created=True, max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('estado', models.CharField(choices=[('Planificado', 'Planificado'), ('Ejecución', 'Ejecucion'), ('Pausado', 'Pausado'), ('Finalizado', 'Finalizado')], default='Planificado', max_length=20)),
                ('unidad_responsable', models.CharField(max_length=100)),
                ('lider', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
            },
        ),
    ]
