# Generated by Django 5.2.4 on 2025-07-25 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0002_alter_proyecto_lider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='estado',
            field=models.CharField(choices=[('Planificado', 'Planificado'), ('Ejecucion', 'Ejecucion'), ('Pausado', 'Pausado'), ('Finalizado', 'Finalizado')], default='Planificado', max_length=20),
        ),
    ]
