# Generated by Django 5.2.4 on 2025-07-25 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0003_alter_proyecto_estado'),
        ('users', '0002_remove_user_nom_gerencia_general_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='unidad_responsable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.unidad', verbose_name='Unidad responsable'),
        ),
    ]
