# Generated by Django 5.2.4 on 2025-07-08 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='es_lider',
            field=models.BooleanField(default=False, help_text='Indica si el usuario es un líder de proyecto'),
        ),
        migrations.AlterField(
            model_name='user',
            name='p00',
            field=models.CharField(help_text='Identificador único del usuario', max_length=100, unique=True),
        ),
    ]
