# Generated by Django 5.2.4 on 2025-07-25 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='nom_gerencia_general',
        ),
        migrations.RemoveField(
            model_name='user',
            name='nom_unidad',
        ),
        migrations.RemoveField(
            model_name='user',
            name='nom_unidad_reporta',
        ),
        migrations.AddField(
            model_name='user',
            name='unidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='miembros', to='users.unidad'),
        ),
    ]
