# Generated by Django 5.2.4 on 2025-07-08 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_es_lider_alter_user_p00'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='es_lider',
        ),
    ]
