# Generated by Django 5.2.4 on 2025-07-08 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_es_lider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='p00',
            field=models.CharField(help_text='Identificador único del usuario', max_length=100, null=True, unique=True),
        ),
    ]
