# Generated by Django 5.2.4 on 2025-07-07 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('prioridad', models.IntegerField(choices=[('1', 'Baja'), ('2', 'Baja Media'), ('3', 'Media'), ('4', 'Media Alta'), ('5', 'Alta')], default='1')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('estado', models.CharField(choices=[('Por hacer', 'Por Hacer'), ('En progreso', 'En Progreso'), ('En revisión', 'En Revision'), ('Completada', 'Completada'), ('Rechazada', 'Rechazada')], default='Por hacer', max_length=20)),
                ('comentarios', models.TextField()),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='proyectos.proyecto')),
                ('sup_tarea', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_tareas', to='tareas.tarea')),
            ],
            options={
                'verbose_name': 'Tarea',
                'verbose_name_plural': 'Tareas',
            },
        ),
    ]
